export type WeatherName = {
    [code: number]: string;
};

export const WeatherIconNameMap: WeatherName = {
    0: "clear.256.png", //'Clear sky',
    1: "few-clouds.256.png", //'Mainly clear, partly cloudy, and overcast',
    2: "clouds.256.png", //'Mainly clear, partly cloudy, and overcast',
    3: "many-clouds.256.png", //'Mainly clear, partly cloudy, and overcast',
    45: "fog.256.png",//'Fog and depositing rime fog',
    48: "fog.256.png",//'Fog and depositing rime fog',
    51: "scattered.256.png",//'Drizzle: Light, moderate, and dense intensity',
    53: "scattered.256.png",//'Drizzle: Light, moderate, and dense intensity',
    55: "scattered.256.png",//'Drizzle: Light, moderate, and dense intensity',
    56: "scattered.256.png",//'Freezing Drizzle: Light and dense intensity',
    57: "scattered.256.png",//'Freezing Drizzle: Light and dense intensity',
    61: "showers-scattered.256.png",//'Rain: Slight, moderate and heavy intensity',
    63: "showers.256.png",//'Rain: Slight, moderate and heavy intensity',
    65: "showers.256.png",//'Rain: Slight, moderate and heavy intensity',
    66: "snow-rain.256.png",//'Freezing Rain: Light and heavy intensity',
    67: "snow-rain.256.png",//'Freezing Rain: Light and heavy intensity',
    71: "snow-scattered.256.png",//'Snow fall: Slight, moderate, and heavy intensity',
    73: "snow.256.png",//'Snow fall: Slight, moderate, and heavy intensity',
    75: "snow.256.png",//'Snow fall: Slight, moderate, and heavy intensity',
    77: "hail.256.png",//'Snow grains',
    80: "10d.png",//'Rain showers: Slight, moderate, and violent',
    81: "10d.png",//'Rain showers: Slight, moderate, and violent',
    82: "10d.png",//'Rain showers: Slight, moderate, and violent',
    85: "13d.png",//'Snow showers slight and heavy',
    86: "13d.png",//'Snow showers slight and heavy',
    95: "11d.png",//'Thunderstorm: Slight or moderate',
    96: "11d.png",//'Thunderstorm with slight and heavy hail',
    99: "11d.png",//'Thunderstorm with slight and heavy hail',
};
export const WeatherNameMap: WeatherName = {
    0: 'Clear sky',
    1: 'Mainly clear',
    2: 'Partly cloudy',
    3: 'Overcast',
    45: 'Fog',
    48: 'Depositing rime fog',
    51: 'Drizzle: Light',
    53: 'Drizzle: Moderate',
    55: 'Drizzle: Dense intensity',
    56: 'Freezing Drizzle: Light',
    57: 'Freezing Drizzle: Dense intensity',
    61: 'Rain: Slight',
    63: 'Rain: Moderate',
    65: 'Rain: Heavy intensity',
    66: 'Freezing Rain: Light and heavy intensity',
    67: 'Freezing Rain: Light and heavy intensity',
    71: 'Snow fall: Slight, moderate, and heavy intensity',
    73: 'Snow fall: Slight, moderate, and heavy intensity',
    75: 'Snow fall: Slight, moderate, and heavy intensity',
    77: 'Snow grains',
    80: 'Rain showers: Slight, moderate, and violent',
    81: 'Rain showers: Slight, moderate, and violent',
    82: 'Rain showers: Slight, moderate, and violent',
    85: 'Snow showers slight and heavy',
    86: 'Snow showers slight and heavy',
    95: 'Thunderstorm: Slight or moderate',
    96: 'Thunderstorm with slight and heavy hail',
    99: 'Thunderstorm with slight and heavy hail',
};